@startuml
start

:初始化程序;
:初始化探针框架;
:创建处理线程;
:读取file_index.txt文件获取pcap文件路径名;
:将报文送入探针框架处理;
:协议栈解析与防御模块处理;
  note right
    * 协议栈解析
    * 防御模块处理
    * 计算报文特征值
  end note
:报文关联会话;
:会话处理;
  note right
    * 规则模块处理
    * 全流量模块处理
    * 协议元数据解析模块处理
    * 元数据发送
  end note
:更新数据库;

end

@enduml